#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate tools/zq_net_fwd_tripwires.h from the linker's undefined-symbol list.

ZQ_CNN_Net is a plain (non-template) class whose Forward() is defined inline in
ZQ_CNN_Net.h, so merely including that header emits a call to *every* layer's
Forward(), which in turn names every ZQ_CNN_Forward_SSEUtils helper.  A gate that
includes ZQ_CNN_Net.h therefore has to define ~45 of them just to link.

They are defined as **tripwires**: each prints its own name to stderr and exits
non-zero.  The gates that use them never run Forward() -- they only call
LoadFrom(), which stops in _check_connect() -- so a tripwire firing means the
gate reached code it was never supposed to, and a silent no-op would have hidden
exactly that.

The symbol set is collected by linking **tools/zq_net_symprobe.cpp**, a probe
that only includes ZQ_CNN_Net.h.  It has to be a separate TU: the gate itself
already includes the generated header, so linking *it* succeeds and yields no
undefined symbols (chicken and egg).

Usage (from WSL):
    python3 tools/gen_net_fwd_tripwires.py             # rewrite the header
    python3 tools/gen_net_fwd_tripwires.py --check     # non-zero if stale
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(HERE, "zq_net_fwd_tripwires.h")
PROBE = os.path.join(HERE, "zq_net_symprobe.cpp")

NL = chr(10)

HEADER_TEXT = '''/* GENERATED by tools/gen_net_fwd_tripwires.py -- do not edit by hand.
 *
 * ZQ_CNN_Forward_SSEUtils 的**绊线桩**（tripwire stub）—— 附录 EN
 *
 * 为什么需要
 * ----------
 * `ZQ_CNN_Net` 是**普通类**（不是模板），`Forward()` 就定义在 ZQ_CNN_Net.h 里。
 * 所以哪怕一道门禁只 include 一下、从头到尾只调 `LoadFrom()`，编译器照样会把
 * `ZQ_CNN_Net::Forward()` 发射出来，而它对**每一层**的 Forward 都有调用 ——
 * 于是每一个 ZQ_CNN_Forward_SSEUtils 的辅助函数都成了未定义符号。
 *
 * 不去编 ZQ_CNN_Forward_SSEUtils.cpp 是有道理的（附录 EC.1）：它一个 TU 引用半个库，
 * 会拖进单编 5 分钟以上的 conv GEMM。
 *
 * 为什么是"绊线"而不是空函数
 * --------------------------
 * 空桩是**静默 no-op**。这些门禁的判据是"`LoadFrom()` 必须在 `_check_connect()`
 * 处返回 false" —— 如果哪天 `_check_connect` 被挪晚了、或者多跑了什么，
 * 于是某个 Forward 真的被调到，空桩会把数据丢掉然后**照样返回 true**，
 * 门禁给出"全绿"，而它其实什么都没验。
 *
 * 绊线桩做的事相反：把自己的名字打到 stderr 并 `_exit(3)`。
 * 跑到就一定红，而且红得能一眼看出是哪个函数。
 *
 * 用到这道桩的门禁里层类型只有 Input / ReLU / Concat，`LoadFrom()` 在
 * `_check_connect()` 就返回，**任何**桩都不该被调到。
 *
 * 重新生成
 * --------
 *     python3 tools/gen_net_fwd_tripwires.py
 *     python3 tools/gen_net_fwd_tripwires.py --check   # 过期就非零退出
 */
#include <cstdio>
#include <cstdlib>
#include <vector>
#include <string>
#include "ZQCNN/ZQ_CNN_Tensor4D.h"
#include "ZQCNN/ZQ_CNN_BBox.h"
#include "ZQCNN/ZQ_CNN_Forward_SSEUtils.h"

// 消息里**不嵌 C 字符串的换行转义**：这个文件是由 Python 生成的，
// 头一次把那段说明写成 Python 三引号里的字面转义序列（两个字符：反斜杠 + n），
// Python 把它当成了真换行，生成出的注释就断成了两行、其中一行不以 // 开头，
// 整个 TU 编不过（报 stray 字符）。同理，也不要在 .replace 里还原转义。
// 需要换行就多发一条 fprintf，不要在生成器里跟转义较劲。
// 换行直接用 fputc(10, ...)：Python 三引号里任何反斜杠转义都会被当成真字符，
// 写成 '反斜杠+n' 会生成一个跨行的字符字面量，TU 直接编不过（报 missing terminating '）。
static void zq_net_tripwire(const char* fn)
{
    fprintf(stderr, "*** zq_net_fwd_tripwires: 不该被调用 %s ***", fn);
    fputc(10, stderr);
    fflush(stderr);
    _exit(3);
}

// 定义成员函数必须出现在类的**外层命名空间**里。
// zq_layerwire_check.cpp 靠 `using namespace ZQ` 让编译器接受，那是宽松写法；
// 这里用显式 namespace，免得依赖编译器的宽松解析。
namespace ZQ
{
'''

SYM_RE = re.compile(r"undefined reference to `([^']+)'")

# 由使用者自己提供真实现的桩，不在这里生成。
#
# `_concat_NCHW_get_size`：ZQ_CNN_Layer_Concat::LayerSetup 在**加载期**就要算输出
# 形状，走的正是它。做成绊线的话，任何"Concat 合法"的用例都会 rc=3 ——
# 而 `zq_concat_alias_check.cpp` 的两个良性对照恰恰必须是合法 Concat。
# 第一版就是把它也做成绊线，红了还一度以为是守卫没修好。
#
# 排除项是**有代价的**：使用者那边的照抄实现要是哪天与真实现漂移了，这里不会发现。
# 所以排除项必须少、且每一条都要在下面写清理由。
EXCLUDE = {
    "_concat_NCHW_get_size",
}


def probe_link_cmd():
    return ('g++ -O0 -mavx2 -mfma -fopenmp -I{root} -I{root}/ZQCNN '
            '-I{root}/ZQ_GEMM -I{root}/3rdparty/include {probe} -o /tmp/zq_net_symprobe').format(
        root=ROOT, probe=PROBE)


def collect_undefined():
    proc = subprocess.run(probe_link_cmd(), shell=True, capture_output=True, text=True)
    log = proc.stderr + proc.stdout
    keep = sorted(set(m for m in SYM_RE.findall(log) if "ZQ_CNN_Forward_SSEUtils" in m))
    if not keep:
        raise SystemExit("探针链接没有产生任何 ZQ_CNN_Forward_SSEUtils 未定义符号 —— "
                         "要么 c++filt/链接器输出格式变了，要么 include 路径不对。"
                         "原始输出前 400 字：\n" + log[:400])
    dem = subprocess.run(["c++filt"] + keep, capture_output=True, text=True).stdout
    sigs = [l for l in dem.splitlines() if l.strip()]

    def fname(sig):
        # **不能**用 sig.split("::")[-1]：参数里的 std::vector<ZQ::ZQ_CNN_Tensor4D*>
        # 自带 ::，会把函数名切碎。取第一个左括号之前、最后一个 :: 之后那一段。
        return sig.split("(")[0].rsplit("::", 1)[-1]

    for s in sigs:
        if fname(s) in EXCLUDE:
            print("excluded (consumer implements it): %s" % fname(s))
    return [s for s in sigs if fname(s) not in EXCLUDE]


DECL_RE = None


def header_return_types():
    """name -> return type, parsed out of ZQ_CNN_Forward_SSEUtils.h.

    c++filt does not print the return type of a non-template function (the
    Itanium mangling does not encode it), so the demangled signature is bare
    `ZQ::...::name(params)`.  Guessing `void` is wrong: `_concat_NCHW` and
    friends return `bool`, and a mismatched return type makes the definition a
    *different* function -- the link then fails with "no declaration matches".
    Read the real return type out of the header instead.
    """
    path = os.path.join(ROOT, "ZQCNN", "ZQ_CNN_Forward_SSEUtils.h")
    text = open(path, "r", encoding="utf-8", errors="replace").read()
    flat = re.sub(r"\s+", " ", text)
    # `static <ret> <name>(`  -- ret is a plain identifier in this header
    found = {}
    for m in re.finditer(r"\bstatic\s+([A-Za-z_]\w*)\s+([A-Za-z_]\w*)\s*\(", flat):
        ret, name = m.group(1), m.group(2)
        if name in found and found[name] != ret:
            raise SystemExit("return type mismatch for %s: %s vs %s"
                             % (name, found[name], ret))
        found[name] = ret
    return found


def to_definition(sig, retmap):
    """'ZQ::ZQ_CNN_Forward_SSEUtils::_relu(int, float*, ...)'
       -> '<ret> ZQ_CNN_Forward_SSEUtils::_relu(int, float*, ...)' + body"""
    if sig.startswith("void ZQ::ZQ_CNN_Forward_SSEUtils::"):
        sig = sig[len("void "):]
    if not sig.startswith("ZQ::ZQ_CNN_Forward_SSEUtils::"):
        raise SystemExit("unexpected demangled form: %r" % sig)
    rest = sig[len("ZQ::ZQ_CNN_Forward_SSEUtils::"):]
    i = rest.index("(")
    name, params = rest[:i], rest[i + 1:]
    params = params.rstrip()
    if not params.endswith(")"):
        raise SystemExit("unbalanced parens in %r" % sig)
    params = params[:-1]
    if name not in retmap:
        raise SystemExit("return type of %s not found in ZQ_CNN_Forward_SSEUtils.h -- "
                         "the header's declaration shape changed; fix header_return_types()"
                         % name)
    ret = retmap[name]
    # 非 void 的桩必须**有返回值**，否则编译器会警告/报错；
    # 但它永远不该被调到，返回 0 只是为了让 TU 能编过。
    body = ('{0} ZQ_CNN_Forward_SSEUtils::{1}({2}){3}{{{3}    zq_net_tripwire("{1}");{4}}}'
            .format(ret, name, params, NL, "" if ret == "void" else " return 0;"))
    if ret != "void":
        body += NL
    return body


def build(sigs):
    retmap = header_return_types()
    out = [HEADER_TEXT]
    for s in sigs:
        out.append(to_definition(s, retmap) + NL)
    out.append("}  // namespace ZQ" + NL)
    return "".join(out)


def main():
    sigs = collect_undefined()
    text = build(sigs)
    if "--check" in sys.argv:
        old = open(OUT, "r", encoding="utf-8").read() if os.path.exists(OUT) else ""
        if old != text:
            print("STALE: %s 与 ZQ_CNN_Net.h 当前的未定义符号表不一致（应为 %d 个桩）"
                  % (OUT, len(sigs)))
            return 1
        print("OK: %s 与探针一致（%d 个桩）" % (OUT, len(sigs)))
        return 0
    with open(OUT, "w", encoding="utf-8", newline=NL) as fh:
        fh.write(text)
    print("wrote %s (%d tripwires)" % (OUT, len(sigs)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
