/* GENERATED by tools/gen_net_fwd_tripwires.py -- do not edit by hand.
 *
 * ZQ_CNN_Forward_SSEUtils 的**绊线桩**（tripwire stub）—— 附录 EN
 *
 * 为什么需要
 * ----------
 * `ZQ_CNN_Net` 是**普通类**（不是模板），`Forward()` 就定义在 ZQ_CNN_Net.h 里。
 * 所以哪怕一道门禁只 include 一下、从头到尾只调 `LoadFrom()`，编译器照样会把
 * `ZQ_CNN_Net::Forward()` 发射出来，而它对**每一层**的 Forward 都有调用 ——
 * 于是每一个 ZQ_CNN_Forward_SSEUtils 的辅助函数都成了未定义符号。
 *
 * 不去编 ZQ_CNN_Forward_SSEUtils.cpp 是有道理的（附录 EC.1）：它一个 TU 引用半个库，
 * 会拖进单编 5 分钟以上的 conv GEMM。
 *
 * 为什么是"绊线"而不是空函数
 * --------------------------
 * 空桩是**静默 no-op**。这些门禁的判据是"`LoadFrom()` 必须在 `_check_connect()`
 * 处返回 false" —— 如果哪天 `_check_connect` 被挪晚了、或者多跑了什么，
 * 于是某个 Forward 真的被调到，空桩会把数据丢掉然后**照样返回 true**，
 * 门禁给出"全绿"，而它其实什么都没验。
 *
 * 绊线桩做的事相反：把自己的名字打到 stderr 并 `_exit(3)`。
 * 跑到就一定红，而且红得能一眼看出是哪个函数。
 *
 * 用到这道桩的门禁里层类型只有 Input / ReLU / Concat，`LoadFrom()` 在
 * `_check_connect()` 就返回，**任何**桩都不该被调到。
 *
 * 重新生成
 * --------
 *     python3 tools/gen_net_fwd_tripwires.py
 *     python3 tools/gen_net_fwd_tripwires.py --check   # 过期就非零退出
 */
#include <cstdio>
#include <cstdlib>
#include <vector>
#include <string>
#include <unistd.h>
#include "ZQCNN/ZQ_CNN_Tensor4D.h"
#include "ZQCNN/ZQ_CNN_BBox.h"
#include "ZQCNN/ZQ_CNN_Forward_SSEUtils.h"
#include "ZQCNN/ZQ_CNN_Forward_SSEUtils_NCHWC.h"

// 消息里**不嵌 C 字符串的换行转义**：这个文件是由 Python 生成的，
// 头一次把那段说明写成 Python 三引号里的字面转义序列（两个字符：反斜杠 + n），
// Python 把它当成了真换行，生成出的注释就断成了两行、其中一行不以 // 开头，
// 整个 TU 编不过（报 stray 字符）。同理，也不要在 .replace 里还原转义。
// 需要换行就多发一条 fprintf，不要在生成器里跟转义较劲。
// 换行直接用 fputc(10, ...)：Python 三引号里任何反斜杠转义都会被当成真字符，
// 写成 '反斜杠+n' 会生成一个跨行的字符字面量，TU 直接编不过（报 missing terminating '）。
static void zq_net_tripwire(const char* fn)
{
    fprintf(stderr, "*** zq_net_fwd_tripwires: 不该被调用 %s ***", fn);
    fputc(10, stderr);
    fflush(stderr);
    _exit(3);
}

// 定义成员函数必须出现在类的**外层命名空间**里。
// zq_layerwire_check.cpp 靠 `using namespace ZQ` 让编译器接受，那是宽松写法；
// 这里用显式 namespace，免得依赖编译器的宽松解析。
namespace ZQ
{
void ZQ_CNN_Forward_SSEUtils::_addbias(int, float*, int, int, int, int, int, int, int, float const*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_addbias");}
void ZQ_CNN_Forward_SSEUtils::_addbias_prelu(int, float*, int, int, int, int, int, int, int, float const*, float const*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_addbias_prelu");}
void ZQ_CNN_Forward_SSEUtils::_avgpooling(int, float const*, int, int, int, int, int, int, int, int, int, int, int, float*, int, int, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_avgpooling");}
void ZQ_CNN_Forward_SSEUtils::_batchnorm_b_a(int, float*, int, int, int, int, int, int, int, float const*, float const*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_batchnorm_b_a");}
bool ZQ_CNN_Forward_SSEUtils::_concat_NCHW(std::vector<ZQ::ZQ_CNN_Tensor4D*, std::allocator<ZQ::ZQ_CNN_Tensor4D*> > const&, int, ZQ::ZQ_CNN_Tensor4D&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_concat_NCHW"); return 0;}

void ZQ_CNN_Forward_SSEUtils::_convolution_nopadding(int, float const*, int, int, int, int, int, int, int, float const*, int, int, int, int, int, int, int, int, int, int, int, float*, int, int, int, int, int, int, int, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_convolution_nopadding");}
void ZQ_CNN_Forward_SSEUtils::_deconvolution_with_padding(int, float const*, int, int, int, int, int, int, int, float const*, int, int, int, int, int, int, int, int, int, int, int, float*, int, int, int, int, int, int, int, int, int, int, int, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_deconvolution_with_padding");}
void ZQ_CNN_Forward_SSEUtils::_depthwise_convolution_nopadding(int, float const*, int, int, int, int, int, int, int, float const*, int, int, int, int, int, int, int, int, int, int, int, float*, int, int, int, int, int, int, int, float const*, float const*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_depthwise_convolution_nopadding");}
bool ZQ_CNN_Forward_SSEUtils::_detection_output(ZQ::ZQ_CNN_Tensor4D const&, ZQ::ZQ_CNN_Tensor4D const&, ZQ::ZQ_CNN_Tensor4D const&, int, int, int, bool, int, ZQ::ZQ_CNN_BBoxUtils::PriorBoxCodeType, bool, float, float, int, float, int, ZQ::ZQ_CNN_Tensor4D&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_detection_output"); return 0;}

bool ZQ_CNN_Forward_SSEUtils::_detection_output_MXNET(ZQ::ZQ_CNN_Tensor4D const&, ZQ::ZQ_CNN_Tensor4D const&, ZQ::ZQ_CNN_Tensor4D const&, std::vector<float, std::allocator<float> > const&, bool, float, int, float, int, ZQ::ZQ_CNN_Tensor4D&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_detection_output_MXNET"); return 0;}

void ZQ_CNN_Forward_SSEUtils::_eltwise_max(int, int, float const**, int, int, int, int, int const*, int const*, int const*, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_eltwise_max");}
void ZQ_CNN_Forward_SSEUtils::_eltwise_mul(int, int, float const**, int, int, int, int, int const*, int const*, int const*, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_eltwise_mul");}
void ZQ_CNN_Forward_SSEUtils::_eltwise_sum(int, int, float const**, int, int, int, int, int const*, int const*, int const*, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_eltwise_sum");}
void ZQ_CNN_Forward_SSEUtils::_eltwise_sum_with_weight(int, int, float const**, float const*, int, int, int, int, int const*, int const*, int const*, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_eltwise_sum_with_weight");}
void ZQ_CNN_Forward_SSEUtils::_inner_product(int, float const*, int, int, int, int, int, int, int, float const*, int, int, int, int, float*, int, int, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_inner_product");}
void ZQ_CNN_Forward_SSEUtils::_lrn_across_channels(int, int, float, float, float, float const*, int, int, int, int, int, int, int, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_lrn_across_channels");}
void ZQ_CNN_Forward_SSEUtils::_lstm_TF(int, float const*, int, int, int, int, int, float const*, int, int, float const*, int, int, float const*, int, int, float const*, int, int, float const*, int, int, float const*, int, int, float const*, int, int, float const*, int, int, float const*, float const*, float const*, float const*, float*, int, int, int, bool, float, float, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_lstm_TF");}
void ZQ_CNN_Forward_SSEUtils::_maxpooling(int, float const*, int, int, int, int, int, int, int, int, int, int, int, float*, int, int, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_maxpooling");}
void ZQ_CNN_Forward_SSEUtils::_normalize(int, bool, bool, float*, float const*, int, int, int, int, int, int, int, float)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_normalize");}
void ZQ_CNN_Forward_SSEUtils::_prelu(int, float*, int, int, int, int, int, int, int, float const*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_prelu");}
bool ZQ_CNN_Forward_SSEUtils::_prior_box(ZQ::ZQ_CNN_Tensor4D const&, ZQ::ZQ_CNN_Tensor4D const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, bool, int, bool, int, int, float, float, float, ZQ::ZQ_CNN_Tensor4D&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_prior_box"); return 0;}

bool ZQ_CNN_Forward_SSEUtils::_prior_box_MXNET(ZQ::ZQ_CNN_Tensor4D const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, int, bool, float, float, float, ZQ::ZQ_CNN_Tensor4D&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_prior_box_MXNET"); return 0;}

bool ZQ_CNN_Forward_SSEUtils::_prior_box_text(ZQ::ZQ_CNN_Tensor4D const&, ZQ::ZQ_CNN_Tensor4D const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, bool, int, bool, int, int, float, float, float, ZQ::ZQ_CNN_Tensor4D&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_prior_box_text"); return 0;}

void ZQ_CNN_Forward_SSEUtils::_reduction_mean(int, float const*, int, int, int, int, int, bool, int, int, int, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_reduction_mean");}
void ZQ_CNN_Forward_SSEUtils::_reduction_sum(int, float const*, int, int, int, int, int, bool, int, int, int, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_reduction_sum");}
void ZQ_CNN_Forward_SSEUtils::_relu(int, float*, int, int, int, int, int, int, int, float)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_relu");}
void ZQ_CNN_Forward_SSEUtils::_relu6(int, float*, int, int, int, int, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_relu6");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_add(int, float, float const*, int, int, int, int, int, int, int, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_add");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_add(int, float, float*, int, int, int, int, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_add");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_max(int, float, float const*, int, int, int, int, int, int, int, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_max");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_max(int, float, float*, int, int, int, int, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_max");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_min(int, float, float const*, int, int, int, int, int, int, int, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_min");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_min(int, float, float*, int, int, int, int, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_min");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_mul(int, float, float const*, int, int, int, int, int, int, int, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_mul");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_mul(int, float, float*, int, int, int, int, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_mul");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_pow(int, float, float const*, int, int, int, int, int, int, int, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_pow");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_pow(int, float, float*, int, int, int, int, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_pow");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_rdiv(int, float, float const*, int, int, int, int, int, int, int, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_rdiv");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_rdiv(int, float, float*, int, int, int, int, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_rdiv");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_rminus(int, float, float const*, int, int, int, int, int, int, int, float*, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_rminus");}
void ZQ_CNN_Forward_SSEUtils::_scalaroperation_rminus(int, float, float*, int, int, int, int, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalaroperation_rminus");}
void ZQ_CNN_Forward_SSEUtils::_scalebias(int, float*, int, int, int, int, int, int, int, float const*, float const*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_scalebias");}
void ZQ_CNN_Forward_SSEUtils::_softmax(int, int, float*, int, int, int, int, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_softmax");}
void ZQ_CNN_Forward_SSEUtils::_sqrt(int, float*, int, int, int, int, int, int, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils::_sqrt");}
void ZQ_CNN_Forward_SSEUtils_NCHWC::AVGPooling(ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1&, int, int, int, int, bool)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::AVGPooling");}
void ZQ_CNN_Forward_SSEUtils_NCHWC::AVGPooling(ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4&, int, int, int, int, bool)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::AVGPooling");}
void ZQ_CNN_Forward_SSEUtils_NCHWC::AVGPooling(ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8&, int, int, int, int, bool)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::AVGPooling");}
bool ZQ_CNN_Forward_SSEUtils_NCHWC::BatchNorm_b_a(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::BatchNorm_b_a"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::BatchNorm_b_a(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::BatchNorm_b_a"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::BatchNorm_b_a(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::BatchNorm_b_a"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Convolution(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC1&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Convolution"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Convolution(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC4&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Convolution"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Convolution(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC8&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Convolution"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithBias(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC1&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithBias"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithBias(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC4&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithBias"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithBias(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC8&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithBias"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithBiasPReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC1&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithBiasPReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithBiasPReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC4&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithBiasPReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithBiasPReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC8&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithBiasPReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithPReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC1&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithPReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithPReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC4&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithPReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithPReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC8&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::ConvolutionWithPReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolution(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC1&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolution"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolution(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC4&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolution"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolution(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC8&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolution"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolutionWithBias(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC1&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolutionWithBias"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolutionWithBias(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC4&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolutionWithBias"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolutionWithBias(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC8&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolutionWithBias"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolutionWithBiasPReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC1&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolutionWithBiasPReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolutionWithBiasPReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC4&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolutionWithBiasPReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolutionWithBiasPReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, int, int, int, int, int, int, ZQ::ZQ_CNN_Tensor4D_NCHWC8&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::DepthwiseConvolutionWithBiasPReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Max(std::vector<ZQ::ZQ_CNN_Tensor4D_NCHWC1 const*, std::allocator<ZQ::ZQ_CNN_Tensor4D_NCHWC1 const*> > const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Max"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Max(std::vector<ZQ::ZQ_CNN_Tensor4D_NCHWC4 const*, std::allocator<ZQ::ZQ_CNN_Tensor4D_NCHWC4 const*> > const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Max"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Max(std::vector<ZQ::ZQ_CNN_Tensor4D_NCHWC8 const*, std::allocator<ZQ::ZQ_CNN_Tensor4D_NCHWC8 const*> > const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Max"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Mul(std::vector<ZQ::ZQ_CNN_Tensor4D_NCHWC1 const*, std::allocator<ZQ::ZQ_CNN_Tensor4D_NCHWC1 const*> > const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Mul"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Mul(std::vector<ZQ::ZQ_CNN_Tensor4D_NCHWC4 const*, std::allocator<ZQ::ZQ_CNN_Tensor4D_NCHWC4 const*> > const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Mul"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Mul(std::vector<ZQ::ZQ_CNN_Tensor4D_NCHWC8 const*, std::allocator<ZQ::ZQ_CNN_Tensor4D_NCHWC8 const*> > const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Mul"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Sum(std::vector<ZQ::ZQ_CNN_Tensor4D_NCHWC1 const*, std::allocator<ZQ::ZQ_CNN_Tensor4D_NCHWC1 const*> > const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Sum"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Sum(std::vector<ZQ::ZQ_CNN_Tensor4D_NCHWC4 const*, std::allocator<ZQ::ZQ_CNN_Tensor4D_NCHWC4 const*> > const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Sum"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Sum(std::vector<ZQ::ZQ_CNN_Tensor4D_NCHWC8 const*, std::allocator<ZQ::ZQ_CNN_Tensor4D_NCHWC8 const*> > const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_Sum"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_SumWithWeight(std::vector<ZQ::ZQ_CNN_Tensor4D_NCHWC1 const*, std::allocator<ZQ::ZQ_CNN_Tensor4D_NCHWC1 const*> > const&, std::vector<float, std::allocator<float> > const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_SumWithWeight"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_SumWithWeight(std::vector<ZQ::ZQ_CNN_Tensor4D_NCHWC4 const*, std::allocator<ZQ::ZQ_CNN_Tensor4D_NCHWC4 const*> > const&, std::vector<float, std::allocator<float> > const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_SumWithWeight"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_SumWithWeight(std::vector<ZQ::ZQ_CNN_Tensor4D_NCHWC8 const*, std::allocator<ZQ::ZQ_CNN_Tensor4D_NCHWC8 const*> > const&, std::vector<float, std::allocator<float> > const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Eltwise_SumWithWeight"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProduct(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProduct"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProduct(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProduct"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProduct(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC::Buffer const&, int, ZQ::ZQ_CNN_Tensor4D_NCHWC4&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProduct"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProduct(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProduct"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProductPrePack(ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC::Buffer&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProductPrePack"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProductWithBias(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProductWithBias"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProductWithBias(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProductWithBias"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProductWithBias(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC::Buffer const&, int, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProductWithBias"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProductWithBias(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8&, void**, long long*)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::InnerProductWithBias"); return 0;}

void ZQ_CNN_Forward_SSEUtils_NCHWC::MaxPooling(ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC1&, int, int, int, int, bool)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::MaxPooling");}
void ZQ_CNN_Forward_SSEUtils_NCHWC::MaxPooling(ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC4&, int, int, int, int, bool)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::MaxPooling");}
void ZQ_CNN_Forward_SSEUtils_NCHWC::MaxPooling(ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&, ZQ::ZQ_CNN_Tensor4D_NCHWC8&, int, int, int, int, bool)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::MaxPooling");}
bool ZQ_CNN_Forward_SSEUtils_NCHWC::PReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, ZQ::ZQ_CNN_Tensor4D_NCHWC1 const&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::PReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::PReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, ZQ::ZQ_CNN_Tensor4D_NCHWC4 const&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::PReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::PReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, ZQ::ZQ_CNN_Tensor4D_NCHWC8 const&)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::PReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::ReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, float)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::ReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::ReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, float)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::ReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::ReLU(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, float)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::ReLU"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Softmax(ZQ::ZQ_CNN_Tensor4D_NCHWC1&, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Softmax"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Softmax(ZQ::ZQ_CNN_Tensor4D_NCHWC4&, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Softmax"); return 0;}

bool ZQ_CNN_Forward_SSEUtils_NCHWC::Softmax(ZQ::ZQ_CNN_Tensor4D_NCHWC8&, int)
{
    zq_net_tripwire("ZQ_CNN_Forward_SSEUtils_NCHWC::Softmax"); return 0;}

}  // namespace ZQ
